# Generated by Django 5.2.12 on 2026-04-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesrequest',
            old_name='phone_numberc',
            new_name='phone_number',
        ),
    ]
