# Generated by Django 5.2.13 on 2026-04-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_phone_numberc_servicesrequest_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceprovider',
            old_name='vtpass_services_id',
            new_name='dododata_services_id',
        ),
        migrations.RenameField(
            model_name='servicesplan',
            old_name='vtpass_variation_code',
            new_name='dododata_variation_code',
        ),
        migrations.RenameField(
            model_name='servicesrequest',
            old_name='vtpass_response',
            new_name='dododata_response',
        ),
    ]
