# Generated by Django 5.2.12 on 2026-03-11 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '08012345678'. and 11 digits.", regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='costomer',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='trxns pin must be 4 digits', regex='\\^d{4}$')]),
        ),
    ]
