# Generated by Django 5.2.12 on 2026-03-11 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_costomer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '08012345678'. and 11 digits.", regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='costomer',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=4, null=True, validators=[django.core.validators.RegexValidator(message="PIN must be entered in the format: '1234'. Exactly 4 digits allowed.", regex='^\\d{4}$')]),
        ),
    ]
