# Generated by Django 5.2.12 on 2026-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_costomer_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='transaction_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
