# Generated by Django 5.2.13 on 2026-04-15 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_costomer_transaction_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonnifyVirtualAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_reference', models.CharField(max_length=100, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('costomer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
