# Generated by Django 5.2.13 on 2026-04-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_monnifyvirtualaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='costomer',
            name='first_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='costomer',
            name='last_name',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='costomer',
            name='username',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
