# Generated by Django 5.2.13 on 2026-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_costomer_first_name_costomer_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='username',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
