# Generated by Django 5.2.13 on 2026-04-26 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_costomer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costomer',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '08012345678'. and 11 digits.", regex='^\\d{11}$')]),
        ),
    ]
