# Generated by Django 5.2.12 on 2026-03-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_description_alter_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY_AIRTIME', 'Airtime'), ('BUY_DATA', 'Data')], max_length=20),
        ),
    ]
