# Generated by Django 5.2.12 on 2026-03-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_transaction_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('BUY_AIRTIME', 'Airtime'), ('BUY_DATA', 'Data')], max_length=20),
        ),
    ]
