# Generated by Django 5.2.9 on 2026-03-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('BUY_AIRTIME', 'Airtime'), ('BUY_DATA', 'Data'), ('WITHDRAWAL', 'Withdrawal'), ('VTU_PURCHASE', 'VTU Purchase'), ('BILL_PAYMENT', 'Bill Payment')], max_length=20),
        ),
    ]
