# Generated by Django 5.2.13 on 2026-05-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('BUY_AIRTIME', 'Airtime'), ('BUY_DATA', 'Data'), ('BILL_PAYMENT', 'Bill Payment')], max_length=20),
        ),
    ]
