# Generated by Django 5.2.13 on 2026-05-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('AIRTIME', 'Airtime'), ('DATA', 'Data'), ('BILL_PAYMENT', 'Bill Payment')], max_length=20),
        ),
    ]
